manifest = "5127b1b9a914d66b52cb8d2f74d16ad7b641283a0708437453d74ed1ac03064b"

[[dependency]]
package = "github.com/buckaroo-pm/boost-asio"
target = "//:asio"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mp11"
target = "//:mp11"

[lock."github.com/buckaroo-pm/boost-algorithm"]
versions = [ "branch=master" ]
revision = "4c68a219b3a1ecb79153be2438faf1c70b95d28f"

[lock."github.com/buckaroo-pm/boost-align"]
versions = [ "branch=master" ]
revision = "6587b84e4fb0711bd7d0930b415ca7937e72021b"

[lock."github.com/buckaroo-pm/boost-any"]
versions = [ "branch=master" ]
revision = "d3dc0d647ec7e85522da3157608b8db88db0bb5a"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "branch=master" ]
revision = "ea0eab9a8cf538aa81a7d53f1762a5ff7e628e73"

[lock."github.com/buckaroo-pm/boost-asio"]
versions = [ "branch=master" ]
revision = "2b4ae750171639f289457b3100d2d7a41a321b8f"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "branch=master" ]
revision = "fc4d65435c49b5b4fbbf0d4867ee8f69bfd42ef1"

[lock."github.com/buckaroo-pm/boost-atomic"]
versions = [ "branch=master" ]
revision = "b440d8827dcfdbddf8f0852178fe5eefd0771fb8"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "branch=master" ]
revision = "783ec0afe46d65f8cfdb558e16f25adc02797b3c"

[lock."github.com/buckaroo-pm/boost-chrono"]
versions = [ "branch=master" ]
revision = "d9135ae23f09a15931dbd15a99324dfe44954aba"

[lock."github.com/buckaroo-pm/boost-concept_check"]
versions = [ "branch=master" ]
revision = "5a8bb5676742a02b9e2d343ecec66639da9deb3e"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "branch=master" ]
revision = "f2f2d0d85496b72eeff1186518deb7e23c757bfd"

[lock."github.com/buckaroo-pm/boost-container"]
versions = [ "branch=master" ]
revision = "fb0dbf2f863db4b7dfc9e3cff17319e2d0a6a3df"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "branch=master" ]
revision = "ddd9a887f1f0253ded4455d455b3c54228067b74"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "branch=master" ]
revision = "82480080750b32b3ef2e3f12157b5c556ae35c0d"

[lock."github.com/buckaroo-pm/boost-date_time"]
versions = [ "branch=master" ]
revision = "62d4c50a60fb887acdf9161fd738beaae72ccac2"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "branch=master" ]
revision = "94aa5268c1a74468be94b40afd730aea1730ceab"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "branch=master" ]
revision = "1795a6e9756f4d9ac60d43e2b9b07ec7ddfdbfb7"

[lock."github.com/buckaroo-pm/boost-function"]
versions = [ "branch=master" ]
revision = "eed94ad6b518aa07bf79c7cb5ab1af3aa594b7be"

[lock."github.com/buckaroo-pm/boost-function_types"]
versions = [ "branch=master" ]
revision = "bb8ffe4d24071f3942a18b274cc7f3ee0dc91eb2"

[lock."github.com/buckaroo-pm/boost-functional"]
versions = [ "branch=master" ]
revision = "28b42e6161041316b359b53682f075522cd48d6f"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "branch=master" ]
revision = "5badcf5b232a15e89d0701bef687ffbe70398696"

[lock."github.com/buckaroo-pm/boost-intrusive"]
versions = [ "branch=master" ]
revision = "4470c0f1a809e06ab91ac67eeef3b1317430de2e"

[lock."github.com/buckaroo-pm/boost-io"]
versions = [ "branch=master" ]
revision = "70c28ebaa83b1fd6907db8f542d7be8abc6835b4"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "branch=master" ]
revision = "c84fc34d0f6386edb15b0cb854a12864b6f15232"

[lock."github.com/buckaroo-pm/boost-lambda"]
versions = [ "branch=master" ]
revision = "aa3ccf90347b018b928354244588f0f48ff6ca18"

[lock."github.com/buckaroo-pm/boost-lexical_cast"]
versions = [ "branch=master" ]
revision = "faf2a66c39c1803227dcd54281894535bcb686b1"

[lock."github.com/buckaroo-pm/boost-math"]
versions = [ "branch=master" ]
revision = "8f4f24c25ab0ce22c93b81738f70302113ed11de"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "branch=master" ]
revision = "3f0711cabd643ed902ff3ae3d6746ba2f7256e4e"

[lock."github.com/buckaroo-pm/boost-mp11"]
versions = [ "branch=master" ]
revision = "d9c3b2cda88f8ff3a6da7560d64cde4d7ea61acf"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "branch=master" ]
revision = "6493fcda0f5cd2ee595346ca48ff495db9fa74d5"

[lock."github.com/buckaroo-pm/boost-numeric_conversion"]
versions = [ "branch=master" ]
revision = "35fa920e0b53c124b0b5972b1802032933c71fca"

[lock."github.com/buckaroo-pm/boost-optional"]
versions = [ "branch=master" ]
revision = "9c3529ad17d35171ffaa689ebfee9f21ce616129"

[lock."github.com/buckaroo-pm/boost-predef"]
versions = [ "branch=master" ]
revision = "73def0812b7235e0312079c729342787819bf1d5"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "branch=master" ]
revision = "a70772bbd315eb597c3f1e359af742dde46a6f37"

[lock."github.com/buckaroo-pm/boost-range"]
versions = [ "branch=master" ]
revision = "545b0fbe13a3efea79f12e76cb837af147d4e4e8"

[lock."github.com/buckaroo-pm/boost-ratio"]
versions = [ "branch=master" ]
revision = "1b80056654a5ca6384e54d925cfdd58feee28f63"

[lock."github.com/buckaroo-pm/boost-rational"]
versions = [ "branch=master" ]
revision = "0d7a63b2751677306b1a1e73b9aef6c91c564710"

[lock."github.com/buckaroo-pm/boost-regex"]
versions = [ "branch=master" ]
revision = "8cc3aec7def0e4075fc565ff27e420ca76e63543"

[lock."github.com/buckaroo-pm/boost-serialization"]
versions = [ "branch=master" ]
revision = "3cb7f143fead7a6a21f99d58bc2154bb6f85a031"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "branch=master" ]
revision = "dc09aaf60934327c4e2e044097c0d5f6a8151702"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "branch=master" ]
revision = "4b9da4628bc69ad0e9b244d3ec885f2eadac95d8"

[lock."github.com/buckaroo-pm/boost-system"]
versions = [ "branch=master" ]
revision = "d98315738ee47380f52e43d790d1c42cf549b175"

[lock."github.com/buckaroo-pm/boost-thread"]
versions = [ "branch=master" ]
revision = "01e9e7a6c1afa9146b7cc9d059c33edbaa3cff07"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "branch=master" ]
revision = "788503e2365554d1860c6d2043999e3430d1f7a5"

[lock."github.com/buckaroo-pm/boost-tokenizer"]
versions = [ "branch=master" ]
revision = "f0c1947d9414a0b40784b2da7a26eaedf1002150"

[lock."github.com/buckaroo-pm/boost-tuple"]
versions = [ "branch=master" ]
revision = "5ffb0abec6da0d9986690b32d20218769a50086b"

[lock."github.com/buckaroo-pm/boost-type_index"]
versions = [ "branch=master" ]
revision = "a8183e0bdcaafdda1183c0279137acadcb5b4466"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "branch=master" ]
revision = "a34caf51f831ffb77d1057c668b5db620863d191"

[lock."github.com/buckaroo-pm/boost-typeof"]
versions = [ "branch=master" ]
revision = "e8cb7bc76c55f02a24f824fecf5cdf0629dc3aa4"

[lock."github.com/buckaroo-pm/boost-unordered"]
versions = [ "branch=master" ]
revision = "7fe9837e937e161a537fcb869a678bfe54d18b2c"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "branch=master" ]
revision = "57aa216434800315c9cd2664169e444e3070a677"

[lock."github.com/buckaroo-pm/boost-winapi"]
versions = [ "branch=master" ]
revision = "92c47b2e1db8a7c023d394e979f81438b410fd18"

[lock."github.com/buckaroo-pm/icu4c"]
versions = [ "branch=master" ]
revision = "d6803681f02ef9395665d4db6e84a4416a679bc3"
